# Generated by Django 3.1.7 on 2021-03-23 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator, django.core.validators.MaxLengthValidator]),
        ),
    ]
